<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 10-Jul-18
 * Time: 12:28
 */

namespace Api\Models;
use Phalcon\Mvc\Model;

class Account extends Model
{
    public $id;

    public $id_company;

    public $name;

    public $type;

//    public $disable_notification;

//    public function beforeUpdate()
//    {
//        if(!$this->disable_notification)
//        parent::beforeUpdate(); // TODO: Change the autogenerated stub
//    }

    public function beforeUpdate()
    {
        $di = $this->getDI();
        $redis = $di->get('redis');
        $redis->delete(":GET:account:");
    }

    public function beforeCreate()
    {
        $di = $this->getDI();
        $redis = $di->get('redis');
        $redis->delete(":GET:account:");
    }

    public function beforeDelete()
    {
        $di = $this->getDI();
        $redis = $di->get('redis');
        $redis->delete(":GET:account:");
    }

}